### ISSUE TITLE
Create a CITATION.cff file

### ISSUE THREAD

**Issue by dkgaraujo** [mit-dci/opencbdc-tx#208]
### Abstract

It would be easier for other researchers to know exactly how the authors want this codebase to be cited, whether pointing to the repo itself or to the technical paper.

This could be achieved by simply creating a CITATION.cff in the root of the project.

### Description

I would propose such a file myself but this seems like a question best solved by the core team.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HalosGhost** [comment]
I'm double-checking with a few people on the team, and we'll take a look at making this clearer/more-accessible!

**Comment by HalosGhost** [comment]
@dkgaraujo till we figure out an ideal way of doing this (`CITATION.cff` leaves a lot to be desired from what I've seen), I'd offer this advice: if you're referencing any of the demonstrated results we reported in the paper or any other findings, I'd cite the paper; otherwise, if you're making specific reference to the implementation (to make up an example, say you are discussing the potential gains of multi-threading any of the individual components we have), citing this repository as your style guide suggests is likely your best bet. For one example, see [MLA's guidance](https://style.mla.org/citing-source-code/).

Unfortunately, authorship of the repository is still something we're figuring out (cf. #147). I'm hoping we'll be able to move to an `AUTHORS` or `THANKS` file as many other projects do, in which case “OpenCBDC Authors” would be correct. However, till then, the most accurate copyright/authorship statement is probably “MIT, FRBB, et al.”.

*Note*: I am **not** a lawyer. The above is the best advice I can offer under the circumstances, speaking as the lead maintainer.

**Comment by HalosGhost** [comment]
via #292
