### ISSUE TITLE
[benchmarking question]

### ISSUE THREAD

**Issue by tanqiwen** [mit-dci/opencbdc-tx#57]
### Affected Branch

trunk

### Basic Diagnostics

- [X] I've pulled the latest changes on the affected branch and the issue is still present.

- [ ] The issue is reproducible in docker

### Description

In order to reproduce the issue, follow these steps:

1. I stress test 2pc architectrure on 8 real machine for 8 sharding,each machine runing one sentinel ,coordinator,locking_shardd
2. runing ./tools/bench/twophase-gen and Statistical throughput count from tx_samples_x.txt,and find the throughput not stable ,as show below ,the first cloumn is count ,the second cloumn is timestamp,why?
     42 1644890386
  43724 1644890393
 119916 1644890394
  30255 1644890395
  13765 1644890396
   2840 1644890397
      2 1644891076
      3 1644891077
      1 1644891101
      8 1644891107
     15 1644891170
     13 1644891172
     12 1644891173
      1 1644891459
      2 1644891473
      1 1644891474
     13 1644891529
     18 1644891540
      3 1644891541
      1 1644891637
      7 1644891638
      4 1644891661
     42 1644891684
      2 1644891826
      3 1644891828
  51904 1644892939
  39527 1644892940
  13126 1644893569
  23061 1644893570
   3549 1644893571
3. The CPU usage of the core where a process coordinator resides and the core where process locking_shardd resides reaches 100%, but other cores are idle. whether CPU binding is used?
<img width="924" alt="lx_clip1644807420082" src="https://user-images.githubusercontent.com/5771139/154024018-c00187d4-fbf7-41bc-a814-548512302019.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by metalicjames** [comment]
In the results file, each line is a single transaction. The first column is the timestamp in nanoseconds since the epoch, and the second column is latency, also in nanoseconds. How are you calculating your statistics above from that?

The locking shard and coordinator are raft-replicated services, and thus single-threaded, hence why only one core is used.

**Comment by tanqiwen** [comment]
i use such “cat   tx_samples_*.txt  |awk '{print substr($1,1,10)}'|sort |uniq -c ” to  statistics

**Comment by tanqiwen** [comment]
> In the results file, each line is a single transaction. The first column is the timestamp in nanoseconds since the epoch, and the second column is latency, also in nanoseconds. How are you calculating your statistics above from that?
> 
> The locking shard and coordinator are raft-replicated services, and thus single-threaded, hence why only one core is used.

i use such cmd “cat tx_samples_*.txt |awk '{print substr($1,1,10)}'|sort |uniq -c ” to statistic

**Comment by metalicjames** [comment]
I think the throughput stability in your test would benefit from two things

1. Use fixed-size transactions to keep the number of unspent outputs in the shards stable, and to prevent the load generators from running out of outputs to spend. You can add the following to your config file to make the load generator send 2-in, 2-out transactions:

    ```
    loadgen_sendtx_input_count=2
    loadgen_sendtx_output_count=2
    loadgen_fixed_tx_rate=1.0
    ```

2. Pre-seed the shards with outputs so that there are many more outputs available to spend. This will ensure the hashmaps inside the shard are already using a large number of buckets, preventing rehashing. It will also further reduce the change the load generators run out of outputs to spend, harming test throughput. You can use the `shard-seeder` in the tools directory to generate pre-seed files for the shards. The shard seeder tool is a little hard to use presently, I'll work on streamlining that a little soon.

**Comment by tanqiwen** [comment]
Can you tell me the approximate steps to use this  shard-seeder tool? i have use shard -seeder to gen pre-seed file  2pc_shard_preseed_1000000_0_255 (two-phase commit),but i don`t know how to use this file. And i also hope to join opencbdc project to complete it.

**Comment by metalicjames** [comment]
I just posted PR #66 which simplifies the usage of the shard seeder tool. You can add the following to your config file to enable pre-seeding:

```
seed_privkey="a0f36553548b3a66c003413140d7b59e43464ca11af66f25a6e746be501596b7"
seed_value=1000000
seed_from=0
seed_to=100000000
```

This will configure a pre-seed with 100000000 UTXOs, each of value 1000000. You can then run the shard seeder tool as follows: `shard-seeder [config file]`. The shard seeder will generate a series of files corresponding to each shard, which should be placed in the working directory from which each shard is launched. The filename contains the number of seeded outputs and the ID of the shard each file is for.

**Comment by tanqiwen** [comment]
thank you very much ，the pre-seed method indeed improves pressure measurement performance. In addition, you need to add loadgen_count=1 configuration
