### ISSUE TITLE
Integrate with java system

### ISSUE THREAD

**Issue by trungnt1811** [mit-dci/opencbdc-tx#74]
Hi team,
I want to build a system written in Java to integrate with open cbdc-tx. Is there any way to execute these operations (mint, transfer, redeem) using Java? 
Thank you.

**Comment by HalosGhost** [comment]
Hello! You can think of the test wallet as being available for integration in two ways: as a CLI executable (that can be called from the shell like any other CLI tool, and will work so long as it can connect to a running sentinel), and as a static library (a `.a`/`.lib`).

It's been quite a while since I've worked with Java; but, if memory serves, [JNI](https://stackoverflow.com/questions/24608851/using-c-library-in-java) is the standard way of interacting with a C++ library in Java. That involves writing wrapper classes in C++ that expose things appropriately for Java to use.

The alternative would be to just start a [`Process`](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html) calling the CLI executable. Which will make more sense for your use-case will depend on what you want to do in your integration.

I hope that is helpful for getting underway!

**Comment by lehoangtran289** [comment]
Hi @HalosGhost and team, 

Regarding to this issue, i'm currently facing difficulties as well in attempting to integrate the open cbdc-tx with our system which was written in Java. 

From your afforementioned comment, one suggestion would be wrapping client classes in C++ then use JNI to interact with it, but i'm wondering if it is reasonable to write the whole client using Java instead of C++ and interact with the core open cbdc-tx through RPC? Provided that it is a feasible solution, would you have any suggestion on how to start from scratch?

I appreciate your attention and look forward to your reply! Thank you

**Comment by HalosGhost** [comment]
There's no reason you cannot write a client from-scratch; You'd probably spend a fair bit of time looking at the [`client`](https://github.com/mit-dci/opencbdc-tx/tree/trunk/src/uhs/client) directory.

However, you should be aware that we don't version anything (this project is very much a research endeavor), so each new commit may include a change that breaks the API.
